seata:
  application-id: springboot-feign-seata-storage
  tx-service-group: default_tx_group
  data-source-proxy-mode: AT
server:
  port: 8084
spring:
  application:
    name: springboot-feign-seata-storage
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${mysql.password:rootroot}
    url: jdbc:mysql://${mysql.address:127.0.0.1}:31497/seata?useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: ${mysql.user:root}
