server:
  port: 8080
management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: "readinessState"
      probes:
        enabled: true